name: AWS S3
description: A Buildkite plugin which can download and upload files from and to S3
author: https://github.com/viviedu
requirements:
  - aws
  - bash
configuration:
  properties:
    download:
      oneOf:
        - type: string
        - type: array
          items:
            type: string
    sync:
      oneOf:
        - type: string
        - type: array
          items:
            type: string
  oneOf:
    - required:
      - download
    - required:
      - sync
  additionalProperties: false
